---

version: "3"

services:
  flatpak_auth:
    build:
      context: .
      dockerfile: Dockerfile-development
    stdin_open: true
    tty: true
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
    volumes:
      - ./assets:/opt/flatpak-auth/assets
      - ./config:/opt/flatpak-auth/config
      - ./lib:/opt/flatpak-auth/lib
      - ./priv:/opt/flatpak-auth/priv
      - ./test:/opt/flatpak-auth/test
    command: do ecto.create, phx.server
    working_dir: /opt/flatpak-auth
    depends_on:
      - postgres

  postgres:
    image: timescale/timescaledb:latest-pg11
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
