---

name: CI

on:
  pull_request:
  push:
    branches-ignore:
      - master

jobs:
  Format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Compile
        run: docker-compose build

      - name: Format
        run: docker-compose run accounts format

  Credo:
    name: Lint (Credo)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Compile
        run: docker-compose build

      - name: Lint
        run: docker-compose run accounts credo

  Dialyzer:
    name: Lint (Dialyzer)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Compile
        run: docker-compose build

      - name: Lint
        run: docker-compose run accounts dialyzer
        continue-on-error: true

  Doctor:
    name: Lint (Doctor)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Compile
        run: docker-compose build

      - name: Lint
        run: docker-compose run accounts doctor
        continue-on-error: true

  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Compile
        run: docker-compose build

      - name: Test
        run: docker-compose run accounts test
