---

name: CI

on:
  - pull_request
  - push

jobs:
  Format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Compile
        run: docker-compose build

      - name: Format
        run: docker-compose run flatpak_auth format

  Credo:
    name: Lint (Credo)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Compile
        run: docker-compose build

      - name: Lint
        run: docker-compose run flatpak_auth credo

  Dialyzer:
    name: Lint (Dialyzer)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Compile
        run: docker-compose build

      - name: Lint
        run: docker-compose run flatpak_auth dialyzer

  Doctor:
    name: Lint (Doctor)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Compile
        run: docker-compose build

      - name: Lint
        run: docker-compose run flatpak_auth doctor
        continue-on-error: true

  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Compile
        run: docker-compose build

      - name: Test
        run: docker-compose run flatpak_auth test
