---

name: Publish

on:
  push:
    branches:
      - master

jobs:
  Format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Compile
        run: docker-compose build

      - name: Format
        run: docker-compose run flatpak_auth format

  Credo:
    name: Lint (Credo)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Compile
        run: docker-compose build

      - name: Lint
        run: docker-compose run flatpak_auth credo

  Dialyzer:
    name: Lint (Dialyzer)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cache
        uses: actions/cache@v1
        id: cache
        with:
          key: dialyzer
          path: _build

      - name: Compile
        run: docker-compose build

      - name: Lint
        run: docker-compose run flatpak_auth dialyzer
        continue-on-error: true

  Doctor:
    name: Lint (Doctor)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Compile
        run: docker-compose build

      - name: Lint
        run: docker-compose run flatpak_auth doctor
        continue-on-error: true

  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Compile
        run: docker-compose build

      - name: Test
        run: docker-compose run flatpak_auth test

  Publish:
    runs-on: ubuntu-latest
    needs:
      - Format
      - Credo
      - Dialyzer
      - Doctor
      - Test

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: >
          docker build \
            --tag elementary/flatpak-auth:latest \
            --tag elementary/flatpak-auth:${{ github.sha }} \
            --file Dockerfile-production .

      - name: Login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish
        run: docker push elementary/flatpak-auth:latest
